spring.config.import=optional:file:.env[.properties]
spring.application.name=BE_Eproject_Sem4

# DataSource
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok&useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.session.store-type=none

# JWT & OpenAI
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

openai.api.key=${OPENAI_API_KEY}
openai.model=${OPENAI_MODEL:gpt-4o-mini}
json.fcm =${JSON_FCM}
server.port=${PORT:8080}

spring.main.allow-circular-references=true
vnpay.tmn-code = ${VNP_TMN_CODE}
vnpay.hash-secret = ${VNP_HASH_SECRET}
vnpay.url = https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url = https://mystictarots.xyz/readerdashboard/payment/vnpay-callback
# Redis Connection Configuration
spring.data.redis.url=${REDIS_URL}

# Lettuce Connection Pool Configuration
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2

# Java Mail Sender Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ntn8530@gmail.com
spring.mail.password=aqwbkloixnylyyum

# Thêm cấu hình SMTP Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Test connection
spring.mail.test-connection=false