# Tên ?ng d?ng
spring.application.name=BE_Eproject_Sem4
  
  # DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/mysteryshack?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok&useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Tnc2024@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  
  # JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
  
  # Format SQL trong log cho d? ??c
spring.jpa.properties.hibernate.format_sql=true
  
  # T?t hoàn toàn Spring Session (không t?o b?ng spring_session n?a)
spring.session.store-type=none

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

openai.api.key=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
openai.model=gpt-4o-mini